### ISSUE TITLE
Error on Location(s) 

### ISSUE THREAD

**Issue by xc1427** [alien4cloud/samples#12]
I followed this guide to configure the sample deployment,
https://alien4cloud.github.io/#/documentation/1.4.0/getting_started/new_getting_started.html

At step *Setup and deploy your application*, I got warnings triangle and the "Matching" tab is disabled.

![screen shot 2017-08-14 at 11 00 11](https://user-images.githubusercontent.com/5611770/29256858-0aebca9a-80e0-11e7-91d1-a485aba8a85f.png)

I also noticed that **Puccini simple orchestrator** is disabled and cannot be re-enabled.
<img width="1054" alt="screen shot 2017-08-14 at 11 06 18" src="https://user-images.githubusercontent.com/5611770/29256930-a629b652-80e0-11e7-8290-2c841ae90211.png">

**Comment by igorng** [comment]
Hello,
glad to see you are looking inot Alien4cloud :)
The orchestrator enablement seems to have gone wrong. Can you check the logs file **alien4cloud-getstarted/alien4cloud/logs/alien4cloud.log**  and see if you can spot any error log? 

I Just re-tried the procedure on my end, and I do not have any problem... Could you retry and let me know if you face the issue again?

Thx

**Comment by xc1427** [comment]
Thanks you for reply. You are doing a great job. Instead investigating on the logs, I re-executed the script to see if there is something wrong. 

You are right, the orchestrator is not enabled by the [getting_started.sh script](https://raw.githubusercontent.com/alien4cloud/alien4cloud.github.io/sources/files/1.4.0/getting_started.sh) 

Actually, I noticed that the following code doesn't set the proper orchestrator id. it outputs `Created orchestrator with id None` on terminal.

```bash
echo "Create puccini orchestrator"
ORCHESTRATORID=`curl "$ALIEN_URL/rest/latest/orchestrators" \
-b curlcookie.txt \
-XPOST \
-H 'Content-Type: application/json; charset=UTF-8' \
-H 'Accept: application/json, text/plain, */*' \
--data-binary '{"name":"Puccini simple orchestrator","pluginId":"alien4cloud-plugin-puccini","pluginBean":"puccini-orchestrator"}' | \
    python -c "import sys, json; print json.load(sys.stdin)['data']"`

echo "Created orchestrator with id $ORCHESTRATORID"
````

I have installed Python, I cannot figure out why.

This leads to the anormal exit of the script, though alien4cloud is successfully started on port 8088. Following are the final part of terminal output
```bash
starting alien4cloud
Waiting for alien4cloud to start
............Initializing getting started data
Create puccini orchestrator
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193    0    79  100   114    607    876 --:--:-- --:--:-- --:--:--   883
Created orchestrator with id None
Update orchestrator configuration
Enable orchestrator (takes a few secs as it checks and configure puccini)
Create local docker location
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135    0    82  100    53   1675   1083 --:--:-- --:--:-- --:--:--  1708
Created location None
Creating compute location resource
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   304    0    78  100   226   2019   5850 --:--:-- --:--:-- --:--:--  5947
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object has no attribute '__getitem__'
Configure template
```

**Comment by igorng** [comment]
Ok that is weird! Just to be sure, do you have all that is mentioned in the **Prerequisites** section? Specially the Docker part?
Can you please attach the log file **alien4cloud-getstarted/alien4cloud/logs/alien4cloud.log**? I'll try to investigate on it.

Thx.

**Comment by xc1427** [comment]
@igorng Thank you for your advice, the docker part. My problem is solved.

I removed completed the `alien4cloud-getstarted` repository, **launch docker** and re-execute the script. Ça roule ! ;)
